version: '3.7'
services:

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: investiment
      POSTGRES_USER: investiment
    ports:
      - 5432
